== Configuration

To configure the plugin add a <configuration> block for the plugin under the <build> in pom.xml

=== requirementsAnnotationsFile

The `requirementsAnnotationsFile` parameter specifies the path to the requirements annotations file.
Defaults to the value set below. 

```xml
<configuration>
  <requirementsAnnotationsFile>
    ${project.build.directory}/generated-sources/annotations/resources/annotations.yml
  </requirementsAnnotationsFile>
</configuration>

```

=== svcsAnnotationsFile

The `svcsAnnotationsFile` parameter specifies the path to the svcs annotations file.
Defaults to the value set below. 

```xml
<configuration>
  <svcsAnnotationsFile>
    ${project.build.directory}/generated-test-sources/test-annotations/resources/annotations.yml
  </svcsAnnotationsFile>
</configuration>

```

=== outputDirectory

The `outputDirectory` parameter specifies the path to where to put the generated output
Defaults to the value set below. 

```xml
<configuration>
  <outputDirectory>
    ${project.build.directory}/reqstool
  </outputDirectory>
</configuration>

```

=== datasetPath

The `datasetPath` parameter specifies the path to the dataset
Defaults to the value set below. 

```xml
<configuration>
  <datasetPath>
    ${project.basedir}/reqstool
  </datasetPath>
</configuration>

```

=== project

The `project` parameter specifies the name of the maven project 
Defaults to the value set below. 

```xml
<configuration>
  <project>
    ${project}
  </project>
</configuration>

```

=== testResults

The `testResults` parameter specifies one or more testResult paths

```xml
<configuration>
  <testResults>
    <testResult>path/to/test/result.xml</testResult>
    <testResult>path/to/test/result.xml</testResult>
  </testResults>
</configuration>

```

=== log

The `log` parameter specifies the log
Defaults to the value set below. 

```xml
<configuration>
  <log>
    ${log}
  </log>
</configuration>

```

=== skip

Skip the execution of the plugin.
Defaults to the value set below. 

```xml
<configuration>
  <skip>
    false
  </skip>
</configuration>

```

=== skipAssembleZipArtifact

Skip zip artifact assembly.
Defaults to the value set below. 

```xml
<configuration>
  <skipAssembleZipArtifact>
    false
  </skipAssembleZipArtifact>
</configuration>

```

=== skipAttachZipArtifact

Skip zip artifact attachment.
Defaults to the value set below. 

```xml
<configuration>
  <skipAttachZipArtifact>
    false
  </skipAttachZipArtifact>
</configuration>

```
