# yaml-language-server: $schema=https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/src/main/resources/jsonSchemas/antoraPlaybookSchema.json

site:
  title: Reqstool Java Maven Plugin
  url: https://github.com/luftfartsverket/reqstool-java-maven-plugin
  start_page: reqstool-java-maven-plugin::index.adoc

content:
  sources:
    - url: ~+
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
asciidoc:
  attributes:
    kroki-server-url: https://kroki.lfv.se
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki



