on:
  push:
    branches:
      - main
      - "feature/*"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: mvn clean verify
