name: Check rules for release
on:
  workflow_call:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch and tag
        if: github.event_name == 'push' && !(github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/') && github.ref =~ '^refs/tags/\d+\.\d+\.\d+$')
        run: exit 1
