name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]

jobs:
  linting:
    name: Check linting
    uses: ./.github/workflows/linting.yml
  build:
    name: Build and run tests
    uses: ./.github/workflows/build.yml
  publish:
    needs:
      - linting
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to the Maven Central Repository
        run: mvn clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SYSDEV_PRIVATE_GPG_KEY_PASSPHRASE }}
