name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  push:
    branches:
      - "feature/*"

jobs:
  linting:
    name: Check linting
    uses: ./.github/workflows/linting.yml
  build:
    name: Build and run tests
    uses: ./.github/workflows/build.yml
  publish:
    needs:
      - linting
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Publish to the Maven Central Repository
        run: mvn clean deploy
