name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  push:
    branches:
      - feature/initial

jobs:
  linting:
    name: Check linting
    uses: ./.github/workflows/linting.yml
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      # - name: Publish to the Maven Central Repository
      #   run: mvn --batch-mode deploy
      #   env:
      #     MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
